# Generated by Django 4.1.7 on 2023-07-14 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = ["*"]

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("file", models.FileField(max_length=255, upload_to="hist_images")),
            ],
        ),
        migrations.CreateModel(
            name="Label",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=120, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="HistImage",
            fields=[
                (
                    "image_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="machine_learning.image",
                    ),
                ),
                (
                    "magnification",
                    models.IntegerField(
                        choices=[
                            (40, "40X"),
                            (100, "100X"),
                            (200, "200X"),
                            (400, "400X"),
                            (0, "UNKNOWN"),
                        ],
                        default=0,
                    ),
                ),
                (
                    "stain",
                    models.CharField(
                        blank=True,
                        choices=[("H&E", "Hematoxylin eosin (H&E)"), ("", "Unknown")],
                        max_length=50,
                    ),
                ),
            ],
            bases=("machine_learning.image",),
        ),
        migrations.AddField(
            model_name="image",
            name="label",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rois",
                to="machine_learning.label",
            ),
        ),
    ]
